### ISSUE TITLE
Add Assertions for Maps

### ISSUE THREAD

**Issue by MarkusAmshove** [MarkusAmshove/Kluent#10]
According to PR #9 we should implement more operations to test Maps.

- [x] shouldHaveKey (thanks to @goreRatzete )
- [x] shouldNotHaveKey (thanks to @goreRatzete )
- [x] shouldHaveValue
- [x] shouldNotHaveValue
- [x] shouldContain (pair)

**Comment by goreRatzete** [comment]
Personally I also use the following for Maps to check if it contains an item: 

`infix fun <R, T> Map<R, T>.shouldContain(item: Pair<R, T>) = this[item.first] shouldEqual item.second`
`val expect = 1 to "one"`
 `val map = mapOf(1 to "one", 2 to "two")`
`map shouldContain expect`

To me it feels very natural, given that one can construct maps with the same syntax as a Pair.

**Comment by MarkusAmshove** [comment]
I updated the TODO list for this, thank you.

If you want to make a PR for these things then it's highly welcome, I'm always happy about contributions :-)

**Comment by goreRatzete** [comment]
Sure, I am happy to contribute. I will be done within this week.

**Comment by MarkusAmshove** [comment]
Thank you @goreRatzete , I merged the PR and released v1.10.

You can see the changelog here:
https://github.com/MarkusAmshove/Kluent/wiki/Changelog
