### ISSUE TITLE
Remove Mockito extensions

### ISSUE THREAD

**Issue by vojtapol** [MarkusAmshove/Kluent#101]
Mockito, even with mockito-kotlin is not suitable for Kotlin tests for various reasons. It is an old outdated framework with some bad design decisions (e.g. not strict by default). And does not play nicely with Kotlin. mockito-kotlin fixes only few of the issues. 

I see no reason of bundling Mockito extensions into Kluent. It has nothing to do with Kluent. 

I am using Kluent with a different and much better mocking framework https://github.com/oleksiyp/mockk

But this definition in `Mocking.kt`:
```
val called = CalledKeyword()
```

clashes with Mockk's definition in `API.kt`:
```
/**
 * Part of DSL. Object to represent phrase "wasNot Called"
 */
object Called
typealias called = Called
```

When using these star imports:
```
import io.mockk.*
import org.amshove.kluent.*
```

**Comment by MarkusAmshove** [comment]
Hi, thank you for opening an issue 😃 

We already plan to deprecate and remove the mocking in the future (#73), because we saw the same problems.

At the moment I'm busy until about June, but then I'm going to work on the 2nd major version which also gets rid of mocking

**Comment by vojtapol** [comment]
Awesome! Feel free to close this as a duplicate. Thank you.
