### ISSUE TITLE
CharSequence shouldNotBeNullOrBlank does not return non null

### ISSUE THREAD

**Issue by AndreasVolkmann** [MarkusAmshove/Kluent#104]
I found that when I call `sql.shouldNotBeNullOrBlank()`, the returning value is still nullable, and furthermore it is now a CharSequence. 

With the following rewrite, it will always return the receiver type. 

```
fun <T : CharSequence> T.shouldNotBeBlank(): T = this.apply {
    Assert.assertTrue(
       "Expected the CharSequence to not be blank",
       this.isNotBlank()
    )
}

fun <T : CharSequence> T?.shouldNotBeNullOrBlank(): T =
    this.shouldNotBeNull().shouldNotBeBlank()
```

I will open a pull request later.

**Comment by AndreasVolkmann** [comment]
For now I have only changed `shouldNotBeNullOrBlank` and `shouldNotBeNullOrEmpty`, but imo all chainables could be adapted to return their original type instead of a generic one.

**Comment by MarkusAmshove** [comment]
I do have a bit of time today, I'll look over the other cases.

Can you give me an example where other assertions don't return their original type?
Most of them use `apply`, which should return the original type

**Comment by AndreasVolkmann** [comment]
Most of the CharSequence functions return a CharSequence. 
`apply` will return CharSequence even when called on a String.

**Comment by MarkusAmshove** [comment]
Ah I see.

You can have a quick glimpse over this [commit](https://github.com/MarkusAmshove/Kluent/commit/7c98e17b32fb9bea306aae6fbf45f7ff15409da4)

If it what you're looking for then I'll release the changes this evening, so you can work with it tomorrow

**Comment by MarkusAmshove** [comment]
I'm a bit late but it is now in 1.38 😄
