### ISSUE TITLE
Add shouldHaveTheSameClassAs assertion

### ISSUE THREAD

**Issue by igorwojda** [MarkusAmshove/Kluent#110]
The corresponding assertion exists in AssertJ and it is missing in Kluent, so a transition to Kluent is not 100% possible (without writing custom code)
http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractAssert.html#hasSameClassAs(java.lang.Object)

In kluent we should add these two
```
shouldHaveTheSameClassAs
shouldNotHaveTheSameClassAs
```

**Comment by MarkusAmshove** [comment]
Hi, thanks for reporting!

I've added it into PR #106 which will be the next release :-)

**Comment by MarkusAmshove** [comment]
This is within the just released 1.39
