### ISSUE TITLE
Can you support SBT?

### ISSUE THREAD

**Issue by tonilopezmr** [MarkusAmshove/Kluent#115]
I'm trying to download the library by SBT but [it isn't supported](https://bintray.com/markusamshove/maven/kluent/view#). 

Can you add support to SBT in bintray? 

Thanks!

**Comment by MarkusAmshove** [comment]
Hi, I haven't worked with SBT myself, but I've read up on some docs and according to [this](https://www.scala-sbt.org/1.x/docs/Resolvers.html) you can add jCenter as a repository with `resolvers += Resolver.jcenterRepo` and then add a dependency to Kluent with `libraryDependencies += "org.amshove.kluent" % "kluent" % "1.40"`
