### ISSUE TITLE
Common String operations

### ISSUE THREAD

**Issue by goreRatzete** [MarkusAmshove/Kluent#12]
I am frequently using the following common String operations and their negated equivalents in my tests:
```
String shouldContain CharSequence
String shouldContain Regex
String shouldStartWith String
```

It would be nice to include them in Kluent. 

What do you think?

**Comment by MarkusAmshove** [comment]
Hi @goreRatzete ,

those are good suggestions, thank you!. I'll put them on my list and see if I can get to it tomorrow morning!

**Comment by MarkusAmshove** [comment]
Resolved via

https://github.com/MarkusAmshove/Kluent/pull/13
