### ISSUE TITLE
Update to Kotlin Mockito 2.0

### ISSUE THREAD

**Issue by dpreussler** [MarkusAmshove/Kluent#123]
Kotlin mockito has breaking API changes including new package. 

It would be nice to have use those for mock and any especially needed as of Coroutines support

**Comment by MarkusAmshove** [comment]
I've recently merged a PR which upgraded mockito-kotlin to 2.0 in Kluent 1.43.

Did anything break for you? The tests all seemed fine without modifications

**Comment by dpreussler** [comment]
will check, thanks

**Comment by dpreussler** [comment]
looks good, thanks :)
