### ISSUE TITLE
kluent-js is missing on jcenter

### ISSUE THREAD

**Issue by jcornaz** [MarkusAmshove/Kluent#124]
Currently it is only possible to get artifact for `common`, `jvm` and `android` modules via jcenter.

`kluent-js` is missing: https://jcenter.bintray.com/org/amshove/kluent/

**Comment by MarkusAmshove** [comment]
That is strange, because it is [here](https://bintray.com/markusamshove/maven/kluent-js)

The group id seems to match

**Comment by MarkusAmshove** [comment]
Oh nevermind, it is on bintray but not linked to jcenter, my bad.

I've opened a request at jcenter, I hope that will be fixed soon

**Comment by MarkusAmshove** [comment]
They haven't gotten back to me yet, but you can test it in the meantime with this repository in gradle:

```
repositories { 
    maven { 
        url "https://dl.bintray.com/markusamshove/maven"
    }
}
```

**Comment by MarkusAmshove** [comment]
It is now included in jcenter, so you can try it out :wink:

**Comment by jcornaz** [comment]
Thanks!
