### ISSUE TITLE
Declare kotlin 1.3 contracts

### ISSUE THREAD

**Issue by jcornaz** [MarkusAmshove/Kluent#125]
There are few assertions which would benefit from Kotlin 1.3 contracts.

Here is an example with `shouldNotBeNull()`:

```kotlin
fun <T : Any> T?.shouldNotBeNull(): T {
  contract {
    returns() implies (this@shouldNotBeNull != null)
  }

  return this ?: throw AssertionError("Expected non null value, but value was null")
}
```

This allows the following:

```kotlin
@Test
fun testSomething() {
  val x = foo()
  x.shouldNotBeNull()
  x.callSomething() // <-- Smart cast by the Kotlin compiler
}
```

If you're interested, I'd be happy to open a PR

**Comment by MarkusAmshove** [comment]
That would be a great addition, I'd be happy to review and merge a PR with contracts, because j haven't used them yet myself  :)
