### ISSUE TITLE
Is naming for shouldBeTrue correct?

### ISSUE THREAD

**Issue by igorwojda** [MarkusAmshove/Kluent#137]
I wonder what is the motivation behind `shouldBeTrue`. Wouldn't `shouldEqualTrue` be better?

As far as I see in the kluent naming convention  'Be' refers to instance check while `Equals` refers to value check, right?

In Kotlin underlying implementation `true`/`false` are always represented by single instances,   however conceptually we still care about the value, so `shouldEqualTrue` seems like a logical choice. Am I missing something here? 🤔

**Comment by MarkusAmshove** [comment]
Hi Igor,

when creating Kluent I've looked at different other fluent assertion libraries for different languages to look what assertions they have and what they named it.

I can't think of a library which didn't call it `should be true` and `should be false`, as I think this is natural English (e.g. `this value should be true`, `I thought this value is true`).
