### ISSUE TITLE
Can shouldBeInstanceOf some how utilise kotlin contracts?

### ISSUE THREAD

**Issue by igorwojda** [MarkusAmshove/Kluent#138]
I am not sure if this is possible 🤔
```
actualResponse shouldBeInstanceOf DomainResponse.Success::class.java
 // can we use Kotlin contracts to say that this is indeed the instance of above type, so
// type would be inferred and no manual casting would be needed latter?
actualResponse 
```

**Comment by MarkusAmshove** [comment]
You can use the return value of `shouldBeInstanceOf` as seen [here](https://github.com/MarkusAmshove/Kluent/blob/master/jvm/src/test/kotlin/org/amshove/kluent/tests/assertions/reflection/ShouldBeInstanceOfShould.kt#L24)  :-)
The assertions returns the tested type if the check passes

**Comment by igorwojda** [comment]
Looks good 👍

**Comment by MarkusAmshove** [comment]
Closing this because the current implementation does what is asked for :-)

**Comment by igorwojda** [comment]
To be precise. Current implementation solves this problem by using value assign (it's fine) instead of type inference (would be better).

**Comment by zsmb13** [comment]
Let me ask about this again - could we get support for contracts instead of having to use the returned value? Would make code slimmer in a bunch of cases.

**Comment by vitorhugods** [comment]
> Let me ask about this again - could we get support for contracts instead of having to use the returned value? Would make code slimmer in a bunch of cases.
> 
> I'd be happy to open the PR for this 😃

**+1**

If I get bored in the next few days I might work on it. But it would be nice to get a confirmation that this is wanted.

**Comment by MarkusAmshove** [comment]
> > Let me ask about this again - could we get support for contracts instead of having to use the returned value? Would make code slimmer in a bunch of cases.
> > I'd be happy to open the PR for this 😃
> 
> **+1**
> 
> If I get bored in the next few days I might work on it. But it would be nice to get a confirmation that this is wanted.

I'm not that familiar with the contracts. Would that change the API, e.g. be a breaking change? If you can come up with an example I can have a look at it

**Comment by vitorhugods** [comment]
Super doable, and requires just a few lines, it's shouldn't introduce any breaking changes, maybe the IDE will give some warnings that type checking the type or casting is unnecessary after calling `shouldBeInstanceOf`.

The implementation would be like so:

```kotlin
inline fun <reified T> Any?.shouldBeInstanceOf(): T {
    contract {
        returns() implies (this@shouldBeInstanceOf is T)
    }
    return if (this is T) this else hardFail("Expected $this to be an instance or subclass of ${T::class.qualifiedName}")
}
```

Kluent is currently using Kotlin 1.3.50. And support for generics reified types on contracts was [added in Kotlin 1.4.0](https://youtrack.jetbrains.com/issue/KT-28298).

Going down the rabbit hole, upgrading Kluent to use Kotlin 1.4.0 can be tiresome, as it would mean reorganising the project to use the Multiplatform plugin, as the platform-specific plugins don't exist anymore, and bundling the library into a single module with multiple sourcesets.

**Comment by MarkusAmshove** [comment]
The contract sounds good, the last part about the multiplatform plugin sounds not so good :smile:
I gave it a try for the latest release, beacuse releasing to maven central was broken anyway but I couldn't get it working correctly with the multiplatform plugin instead of modules.

If we can get that working, I would be very glad. In the past I've created a new multiplatform project from scratch in IntelliJ and copied stuff over, but that still didn't make it work properly :)
