### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by caipivara** [MarkusAmshove/Kluent#140]
Hi

It will be cool to have a changelog list to know about what is new on releases or changes on the api, like this is very hard to update the dependency with confidence.

**Comment by MarkusAmshove** [comment]
Hello,

there is a link to a [changelog](https://markusamshove.github.io/Kluent/) in the Readme of the repository. It links to the github page where the changelog comes after some examples.

I'm happy to hear of any suggestions on how to make this more discoverable :-)
Where did you look for a changelog?

**Comment by caipivara** [comment]
@MarkusAmshove I was hoping to find it on the repo itself, in a file called CHANGELOG.md or something like that

**Comment by MarkusAmshove** [comment]
Thank you for the suggestion, I'll copy it over and keep them in sync  :-)
