### ISSUE TITLE
Lack of org.amshove.kluent.shouldNotBeNull

### ISSUE THREAD

**Issue by aishlin** [MarkusAmshove/Kluent#141]
`org.amshove.kluent:kluent` (JVM) dependency does not contain methods like
`shouldNotBeNull` and `shouldBeNull` but it can be found in `org.amshove.kluent:kluent-android`
It is possible to add these methods to `org.amshove.kluent:kluent` dependency?

**Comment by MarkusAmshove** [comment]
Thank you for reporting, that seems like a strange issue. I'll look into it.
Are you using the latest version?

**Comment by aishlin** [comment]
Yes, I'm using the latest version. Thx :)

**Comment by MarkusAmshove** [comment]
Can you post your `build.gradle`?

[This](https://github.com/MarkusAmshove/kluenttesteroni) testproject works fine for me
