### ISSUE TITLE
Is it possible to support multi language ?

### ISSUE THREAD

**Issue by arfirman1402** [MarkusAmshove/Kluent#157]
Hello, I just wanna ask something. Is it possible to support multi language beside english for this library ? For example like bahasa or spanish or italian ? I hope I can support on bahasa if thats really possible.

Thank you.

**Comment by MarkusAmshove** [comment]
Are you talking about documentation or the code itself?

**Comment by firmanbklpk** [comment]
the code for support multi language. For example like this one : 
JUnit:
`assertEquals("hello", "hello");`

Kluent (English):
`"hello" shouldEqual "hello"`

Kluent (Bahasa):
`"hello" samaDengan "hello"`

**Comment by arfirman1402** [comment]
the code for support multi language. For example like this one :
JUnit:
`assertEquals("hello", "hello");`

Kluent (English):
`"hello" shouldEqual "hello"`

Kluent (Bahasa):
`"hello" samaDengan "hello"`

**Comment by MarkusAmshove** [comment]
Ah I see.
I think that would be too much of a maintenance burden for me and also contributors or the changes would have to wait for translation/translates artifact don't get the newest features.

I'm writing code in German at my company for everything we write ourselves, but live with English 3rd party libraries for that particular reason.
If you really need that, I would suggest that you set up a project which uses translated names as a proxy for the English assertions, that way you can depend on a specific version of Kluent and keep your translations in sync with that.
That way the translations don't have to live in this repository/project, but can be curated at your pace within your project  :-)
