### ISSUE TITLE
shouldBeNear fails with not finite values.

### ISSUE THREAD

**Issue by jcornaz** [MarkusAmshove/Kluent#166]
Hi.

I think it is reasonable to say that `x.shouldBeNear(x, delta)` should always pass. 

I think for any value of `x` it is correct to say `x` is near `x`

If you agree with this statement, then we have to fix the current implementation which fails in the following case:

```kotlin
val delta = 1.0
val x = Double.NaN
x.shouldBeNear(x, delta) // Throws an assertion error, because `NaN` is not between `NaN` and `NaN`
```

**Comment by ChristianIvicevic** [comment]
Your issue title does not describe your example. NaN is neither a number nor infinite. Thus it cannot be near itself since there is no semantical definition of NaN being near NaN by a given delta.

If your business logic allows a value to be NaN in the first place you should assert that (first).

**Comment by ChristianIvicevic** [comment]
For reference, AssertJ behaves the same: https://github.com/joel-costigliola/assertj-core/issues/984

**Comment by jcornaz** [comment]
>NaN is neither a number nor infinite

nor finite....

Sorry for my wording, I changed it.


> For reference, AssertJ behaves the same: joel-costigliola/assertj-core#984

Well I don't see how it is helpful. I'm not planning to open an equivalent issue on AssertJ because I don't use it.


>it cannot be near itself

Well, I aggree that it can be a valid decision to say : *Since `NaN != NaN` `NaN` cannot be near isteslf.

It would be a totally fine decision, and I'd accept it.

But it is unpractical in my opinion, and I think it worthwhile consider a behavior, maybe a little bit less aligned with formal mathematical definition, if it allows easier, safer, more pragmatic testing.

Unless you think it could lead to error? In which case can you share an example?

**Comment by MarkusAmshove** [comment]
I don't really know what to do with this issue :/ 
My first thought would be to have the same behaviour as AssertJ in this case

**Comment by jcornaz** [comment]
> My first thought would be to have the same behaviour as AssertJ in this case

Can be a good choice indeed. How does assert behave?

**Comment by MarkusAmshove** [comment]
According to the changes in the linked issue above, it seems to fail/throw an exception :-)

**Comment by jcornaz** [comment]
>According to the changes in the linked issue above, it seems to fail/throw an exception :-)

The linked issue is about comparing `NaN` to finite value like:
`assertThat(Double.NaN).isCloseTo(0.007, Percentage.withPercentage(0.1));`

So, yes, I hope it throws.

Here we are talking about comparing `NaN` with `NaN`. Which is not the same ;-)

**Comment by jcornaz** [comment]
@MarkusAmshove Actually I just looked at the unit tests  written to solve the linked issue and I found:

```
https://github.com/joel-costigliola/assertj-core/pull/987/files#diff-4f2c8aaeab6ada585032cc790a33db2aR110-R113
```

Which clearly states: "should pass if actual and expected are NaN".

So, yes please. Go for that. This is exactly what I am asking for ;-)

**Comment by MarkusAmshove** [comment]
Great, would you be willing to open a PR? I'm currently busy but can review and merge/release PRs :-)

**Comment by jcornaz** [comment]
>Great, would you be willing to open a PR? I'm currently busy but can review and merge/release PRs :-)

Yes. I think I might find time for it next week.
