### ISSUE TITLE
Sorted Collections assertion

### ISSUE THREAD

**Issue by sandjelkovic** [MarkusAmshove/Kluent#167]
It would be great to have an assertion which can check if the Collection is already sorted. The assertion would also accept a `Comparator` instance to verify with. Similar (or same) as [AssertJ](http://javadox.com/org.assertj/assertj-core/3.1.0/org/assertj/core/api/AbstractListAssert.html#isSortedAccordingTo-java.util.Comparator-)

It would be something along these lines:
```
list shouldBeSortedAccordingTo Comparator.comparingInt { it.position }
```
or
```
list shouldBeSortedBy Comparator.comparingInt { it.position }
```

This could then be chained to a structure like this
```
list.shouldNotBeEmpty()
.shouldHaveSize(10)
.shouldBeSortedAccordingTo(Comparator.comparing<Slot, Int> { it.position })
```

**Comment by MarkusAmshove** [comment]
This is a nice idea, I like it. Would you be willing to open a PR? :-)
