### ISSUE TITLE
Using import org.amshove.kluent.mock leads to a java.lang.NoSuchMethodError in mockitokolin

### ISSUE THREAD

**Issue by jleidgens** [MarkusAmshove/Kluent#168]
I updated mockitokotlin2 to 2.2.0 and after that we saw unit tests failing with 

`java.lang.NoSuchMethodError: com.nhaarman.mockitokotlin2.MockingKt.withSettings([Lkotlin/reflect/KClass;Ljava/lang/String;Ljava/lang/Object;Lorg/mockito/stubbing/Answer;ZLorg/mockito/mock/SerializableMode;Z[Lorg/mockito/listeners/InvocationListener;ZLcom/nhaarman/mockitokotlin2/UseConstructor;Ljava/lang/Object;)Lorg/mockito/MockSettings;`

This only happened in cases where autocomplete mixed up the mock functions and we where using `org.amshove.kluent.mock` once we switched to `com.nhaarman.mockitokotlin2.mock` the tests go through again. 

There is also a ticket inside the mockitokotlin [repository](https://github.com/nhaarman/mockito-kotlin/issues/364) about this.

**Comment by MarkusAmshove** [comment]
What would we have to do on our end to resolve this?

Is it enough to update the mockitokotlin version?

**Comment by jleidgens** [comment]
I'm not sure what is causing this exception, it is definitely a bug in mockito that is happening this way but it still could be a wrong usage of the mockito library.

**Comment by MarkusAmshove** [comment]
Did you try to update mockitokotlin/mockito in Kluent and see what happens?
Otherwise I can try to give it a shot if you could create a small repro which uses Kluent and encounters this problem. Then I can rebuild Kluent locally and see if any updates fix this issue

**Comment by glureau-betclic** [comment]
Reproduced the same issue with latest version of mockito and mockito-kotlin + Kluent. Problem is the call `mock()` offers 2 imports to different implementations. I've removed the kluent one manually. Not sure why Kluent provides this mock method, should we not use the one provided by mockito directly @MarkusAmshove?

**Comment by MarkusAmshove** [comment]
Should be fixed with version 1.65. if not feel free to reopen :-)
