### ISSUE TITLE
Number operations

### ISSUE THREAD

**Issue by goreRatzete** [MarkusAmshove/Kluent#17]
Hi,

I was just writing some tests where I assert that the size of a Collection is not 0, i.e. the Collection is not empty.

`persSpecs.size shouldNotBe 0`

The error message reads: expected not same.

I kind of miss a shouldBeGreaterThan and shouldBeLessThan.

**Comment by MarkusAmshove** [comment]
Hi,

the numerical operations are a good idea, I'll have a look into them. Maybe for collections it would even make sense to have something like `persSpecs shouldHaveSize 0` or `shouldBeEmpty`

As for the error message, `shouldBe` and `shouldNotbe` refer to JUnits assertSame, which tests for referencial equality.  [Wiki](https://github.com/MarkusAmshove/Kluent/wiki/Assertions#assertsame)

`shouldEqual` and `shouldNotEqual` should be the things you're looking for.

**Comment by goreRatzete** [comment]
Thanks for the reply.

Yes I also thought about the `Collection shouldHaveSize x`. 
ShouldBeEmpty would be nice, but it does not take anything, so my solution looks like this:
`Collection.shouldBeEmpty()`. Imo kind of ugly, compared to the other infix functions.

**Comment by MarkusAmshove** [comment]
I'm thinking about implementing non infix stuff as normal extension methods.

I think having them outweights them being not infix.

It would look like this:

```kotlin
theCollection.shouldBeEmpty()
theNumber.shouldBePositive()
```

**Comment by goreRatzete** [comment]
Yeah I agree.

I also frequently use this one: 
`someString.shouldNotBeNullOrEmpty()`

**Comment by MarkusAmshove** [comment]
I merged the numerical operations into master and released it in 1.14

https://github.com/MarkusAmshove/Kluent/wiki/Changelog#114

I need to work on the docs some day, cause since the first release there is so much more stuff now :-)
