### ISSUE TITLE
Support for Instant assertions

### ISSUE THREAD

**Issue by samneirinck** [MarkusAmshove/Kluent#175]
It would be great if we had assertions for the [Instant](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html) class, similar to what’s available currently for ‘LocalDateTime’ and others.

If you agree this would not be a bad idea, I can prepare a PR for this.

**Comment by MarkusAmshove** [comment]
Hi @samneirinck ,

that sounds like a great idea :-)

You can give it a go!
