### ISSUE TITLE
Add support for soft assertions

### ISSUE THREAD

**Issue by igorwojda** [MarkusAmshove/Kluent#178]
Similar to `assertSoftley`
https://twitter.com/kotlintesting/status/1267350165750308864

**Comment by MarkusAmshove** [comment]
Hi igor,

would you like to propose a draft on how this could work in Kluent?

The most important things in this are, in my opinion, that all assertions are run (no matter if some fail) and that there is a unified failure message.
I like the way [Shouldly does this](http://docs.shouldly-lib.net/docs/shouldsatisfyallconditions), including the aggregated error messages.

The way our assertions are currently built, the method would actually have to take vararg functions to accomplish this, like so:

```kt
person.assertAll(
    { it.name.shouldBe("Name") },
    { it.age.shouldBe(18) }
)
```

that way `assertAll` can wrap all assertions, catch their errors and aggregate the messages.

What do you think?

**Comment by igorwojda** [comment]
1. Yes fail of single assertion should not abort the execution (idea behind soft assertion)
2. other factor that we should also consider is the fact that we may want verify data from more then one object.
3. I am not a big fan off these nested lambdas (kotest works without them)


```
shouldAssertSoftly {
	sut.name.shouldBe("Name")
    sut.age.shouldBe(18)
}
```

Also we could probably keep `should` prefix to match rest of kluent assertions
`shouldAssertSoftly` / `shouldAssertAll`

**Comment by MarkusAmshove** [comment]
Do you want to give the implementation following your design a shot? 😊

**Comment by MarkusAmshove** [comment]
This is now part of version 1.65 :-)
