### ISSUE TITLE
Nullable support for shouldBeEqualTo

### ISSUE THREAD

**Issue by cristan** [MarkusAmshove/Kluent#181]
shouldBeEqualTo doesn't support nullable types. The following doesn't compile:

```
val s1: String? = null
val s2: String? = null
s1 shouldBeEqualTo s2
```

I don't know if this is on purpose, but it's easy to support nulls here. Change:

`infix fun String.shouldBeEqualTo(expected: String) = this.apply { assertEquals(expected, this) }`
to
`infix fun String?.shouldBeEqualTo(expected: String?) = this.apply { assertEquals(expected, this) }`

**Comment by MarkusAmshove** [comment]
Which version of Kluent are you using?

I've added the following testcase to a fresh copy of the master branch:

```kt
package org.amshove.kluent.tests

import org.amshove.kluent.shouldBeEqualTo
import org.junit.Test

class NullableTest {
    @Test
    fun passWhenTestingToNullValues() {
        val s1: String? = null
        val s2: String? = null
        s1 shouldBeEqualTo s2
    }
}
```

This does compile and the test is green for me.
I've also double checked it against the most recent Kotlin version, to see if they changed something, but I still can't reproduce this.

Which Platform do you target (JVM/Android/JS) ?

**Comment by cristan** [comment]
I was running `org.amshove.kluent:kluent-android:1.50`... At 1.60 this has been fixed. Thanks for testing and sorry for not checking whether I had the lastest version.
