### ISSUE TITLE
`should throw` doesn't work with functions with parameters

### ISSUE THREAD

**Issue by Egorand** [MarkusAmshove/Kluent#19]
For example, the following will not compile:

```kotlin
val func = { a: Int, b: Int -> a / b }
func(1, 0) `should throw` ArithmeticException::class
```

I've quickly looked into this, but can't find a solution so far. Looks like there's no way to declare a function type with `vararg` params, e.g. `((vararg params: Any) -> Any)`,  but this can be solved with providing multiple versions of `should throw` for functions having from 0 to 9 parameters - this should work for 99.99% cases. However, I can't figure out how to reference the parameters when invoking the function, will keep looking for the solution.

**Comment by MarkusAmshove** [comment]
What I do in this case is something like this:

```kt
var a = 2
var b = 0
val func = { Math.floorDiv(a, b) }

func `should throw` ArithmeticException::class
```

or even

```kt
val func = { someDomainFunction(with, para, meters); Unit }
```

and then assert the Exception.

But I'll look into functions with more parameters and see if the generics allow that

**Comment by MarkusAmshove** [comment]
As of now I'd like to keep the workaround with explicitly returning Unit:

`val func = { someDomainFunction(with, para, meters); Unit }`

I'll have it on my list for later though :-)
