### ISSUE TITLE
Publish to Maven Central or other repositories

### ISSUE THREAD

**Issue by ephemient** [MarkusAmshove/Kluent#190]
JCenter is shutting down: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by MarkusAmshove** [comment]
Thank you for letting me know, I think I'll go with mavencentral and have a look to set things up this weekend

**Comment by mpost** [comment]
Awaiting migration. :)

**Comment by MarkusAmshove** [comment]
I'm on it, the process is a bit longer to set up initially compared to jcenter. I've got the domain for the group id claimed now, next step is signing and publishing actual artifacts to OSSR and then promoting to mavencentral :-)

**Comment by JvmName** [comment]
In case it makes your life any easier, there's a tool that Martin Bonnin developed that seems to make this pretty straightforward: https://github.com/martinbonnin/vespene

**Comment by MarkusAmshove** [comment]
Thanks for the hint, I'll have a look :)

**Comment by MarkusAmshove** [comment]
I've uploaded 1.64 (the previous version) and went through all the staging processes, it hopefuly shows up in mavencentral in a couple of hours 😄

**Comment by MarkusAmshove** [comment]
It already shows up while browsing: https://repo1.maven.org/maven2/org/amshove/kluent/

**Comment by slavonic-suomi** [comment]
Could you please also upload some previous versions? I can't switch from 1.59 right now. Thank you

**Comment by jcornaz** [comment]
@slavonic-suomi The old versions will still be served by jcenter until the 1st of february **2022**. So you have time ;-)

**Comment by MarkusAmshove** [comment]
Sure, I’ll add this to my todo list

**Comment by MarkusAmshove** [comment]
1.59 and 1.65 (latest) should show up on mavencentral any time now :)

**Comment by peterfortuin** [comment]
This seems to be working for me. Thank you for the work!
