### ISSUE TITLE
Cannot use Kluent's mockito-kotlin wrapper since 1.65

### ISSUE THREAD

**Issue by committedteadrinker** [MarkusAmshove/Kluent#191]
Since release 1.65 Kluent does not support any usage of its [mocking wrapper](https://markusamshove.github.io/Kluent/Mocking.html) anymore. I'm not sure whether this is intentional or not. This issue seems to be related to the change that was done for another issue: https://github.com/MarkusAmshove/Kluent/issues/168

If this is intentional, it would be good to remove the documentation pages that shows how Kluent wrap its mockito-kotlin. If it is not, would it be possible to put the wrapper functions back to the main folder without causing the previous issue again?

**Comment by MarkusAmshove** [comment]
Thank you for addressing this! I will remove the documentation.
Sadly the linked issue (and others) have been a pain for a few years now where we always had to find new fixes for new versions, so removing mocking was on the roadmap for a long time.
There are however other libraries for exactly this purpose, like [MockK](https://github.com/mockk/mockk)

**Comment by committedteadrinker** [comment]
Thanks for the reply! It would be good to mark these features as `@Deprecated("...")` next time so that users of this library know that they're going to be unavailable. (This is for next time ofc). I did not expect a minor version update would be breaking existing functionality.

**Comment by MarkusAmshove** [comment]
I agree and that was planned for 2.0, but I guess things got a bit too twisted up.

I'll update the documentation for mocking to include the last version it can be used (1.64). Also have to make sure to release that version to mavencentral once that is set up

**Comment by MarkusAmshove** [comment]
I've now added a notice to the [Changelog](https://github.com/MarkusAmshove/Kluent/blob/master/CHANGELOG.md) and [Documentation](https://github.com/MarkusAmshove/Kluent/blob/master/docs/Mocking.md) to pin to v1.64.
