### ISSUE TITLE
Improve errors

### ISSUE THREAD

**Issue by igorwojda** [MarkusAmshove/Kluent#193]
While testing complex models it's quite hard to say where the problem lies exactly (which model property does not match expected value):

Now:
```
java.lang.AssertionError: 
The following assertion failed:
Expected <[Album(name=albumName, artist=artistName, wiki=AlbumWiki(published=published), mbId=1)]>, actual <[Album(name=albumName, artist=artistName, wiki=null, mbId=1)]>.
```

If two object are of the same type we could try to display each property in separate line (maybe even add tabs for nested models/properties). Goal here is to instantly know which property does not have expected value:

Expected 
```
java.lang.AssertionError: 
The following assertion failed:
Expected:
name=albumName - OK
artist=artistName - OK
wiki=null but it was AlbumWiki(published=published, summary=summary)

```

**Comment by MarkusAmshove** [comment]
Did you use `shouldBe` or `shouldEqual`?

You can try `shouldBeEquivalentTo` as it might [have the formatting you need](https://github.com/MarkusAmshove/Kluent/blob/master/jvm/src/test/kotlin/org/amshove/kluent/tests/equivalency/ShouldBeEquivalentTo.kt#L920).

We could also try to reuse the formatting for Objects that are not found to be equal with `shouldBe` or `shouldEqual`

**Comment by igorwojda** [comment]
Tried `shouldBeEquivalentTo`, but:

![image](https://user-images.githubusercontent.com/530122/108733416-29362f00-7537-11eb-966b-da66444ec5ac.png)

🤔

**Comment by drcolombo** [comment]
`shouldBeEquivalentTo` doesn't support backtick notation, only pure JVM, as it expects 2 parameters, not only one: an `expected` object and `config` of `EquivalencyAssertionOptions` type.
In other words, this should work fine:
`result.shouldBeEquivalentTo(albums)`

**Comment by drcolombo** [comment]
If my suggestion works, then @MarkusAmshove , could you please close the issue?

**Comment by MarkusAmshove** [comment]
I'll interpret igors emoji reaction as "case closed" :-)
