### ISSUE TITLE
All assertions should support assertSoftly 

### ISSUE THREAD

**Issue by piotrb5e3** [MarkusAmshove/Kluent#196]
Hi,
Thanks to #178 Kluent now has the `assertSoftly` construct. It was released recently as part of 1.65.

Unfortunately, some assertions still do not support `assertSoftly`, as the support was only added for methods relying on `assertTrue`, but not for these relying on `fail` (eg `shouldHaveSize` works for subtypes of `Sequence`, but not `Iterable`).

This makes it unintuitive to use `assertSoftly`.

**Comment by MarkusAmshove** [comment]
Your PR #179 was released with 1.66, which should close this issue :-) Thank you for the contribution!

**Comment by piotrb5e3** [comment]
I'd like to reopen this issue.
#197 was only fixing a problem that I saw when trying to add a test case for this issue. The test case added in #198 fails when added to current master.

**Comment by MarkusAmshove** [comment]
Sorry for being to fast :-) The [build ](https://github.com/MarkusAmshove/Kluent/actions/runs/933534963) seemed fine, aside from SonarCloud (which was an issue on my side)

**Comment by MarkusAmshove** [comment]
You can give 1.67 a try now :)

**Comment by piotrb5e3** [comment]
It works well. I think we can close it :+1:
