### ISSUE TITLE
Consistent file and code formatting

### ISSUE THREAD

**Issue by javatarz** [MarkusAmshove/Kluent#206]
### File formatting
A lot of our code files do not end with a new line like the unix standard requests.

### Code formatting
I have noticed inconsistencies such as opening braces being on the [same line](https://github.com/MarkusAmshove/Kluent/blob/master/jvm/src/test/kotlin/org/amshove/kluent/tests/assertions/file/ShouldHaveExtensionShould.kt) vs [different lines](https://github.com/MarkusAmshove/Kluent/blob/master/jvm/src/test/kotlin/org/amshove/kluent/tests/assertions/file/ShouldHaveNameShould.kt). 

### File formatting

Would it make sense to add an `.editorconfig` file to this project to [consistently format files across most popular IDEs](https://editorconfig.org/)? I'm thinking that the following rules will probably be minimally disruptive

```
root = true

[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 4
```

### Code formatting

Use the IntelliJ formatter across the project to start off. Check for formatting linters to fail PRs if they are inconsistently formatted and have tooling locally that integrates with gradle so people can get early feedback

---
@MarkusAmshove: What are your thoughts on this? I can turn around a PR pretty quickly if you like this idea. Please let me know.

**Comment by javatarz** [comment]
#207 has added a `.editorconfig`, fixed the formatting and made the line endings standardized (LF). Pending item in this issue is to break the pipeline if someone violates this formatting.

**Comment by MarkusAmshove** [comment]
I've added the topic `hacktoberfest` to the repository, is that enough? There are multiple topics like `hacktoberfest2020` `hacktoberfest2021` etc :)

**Comment by javatarz** [comment]
The documentation says that `hacktoberfest` should be enough for me to get the contribution but I didn't. Might be because my PR was merged before the tag was available and they have cached it. Can you add `hacktoberfest-accepted` to #207 itself? Hoping that might work.

**Comment by javatarz** [comment]
Their website has now been updated, my PR has been accepted! Thanks so much @MarkusAmshove! <3

**Comment by MarkusAmshove** [comment]
Added with #207 🥳
