### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by pcostaeu** [MarkusAmshove/Kluent#214]
Hi @MarkusAmshove 

Thank you for your work on Kluent. I see that it's been almost a year since last updates to the codebase. It this project still actively maintained? Kicking off a new project and checking what libs I should include

**Comment by MarkusAmshove** [comment]
Hi,

I'm planning to do a maintenance release to address some of the issues, however there won't be any major new features from my side, because the project fits all my needs currently. But I would review PRs about new features :)

**Comment by pcostaeu** [comment]
Thank you for the answer, my question was more regarding addressing some issues and dependencies updates. The feature set is enough :)
