### ISSUE TITLE
JUnit and Mockito versions

### ISSUE THREAD

**Issue by Jeevuz** [MarkusAmshove/Kluent#31]
Hi! Thanks for the nice library!

I wonder why you use
```compile 'junit:junit:4.11'```
and
```compile 'org.mockito:mockito-core:2.1.0'```
while both have a newer versions (4.12 and 2.7.19)?

**Comment by MarkusAmshove** [comment]
Hi,

I just haven't updated them yet. But I'll do :-)

**Comment by Jeevuz** [comment]
Haha, great! )
