### ISSUE TITLE
Junit 5

### ISSUE THREAD

**Issue by MarkusAmshove** [MarkusAmshove/Kluent#4]
Once junit 5 is released in a stable manner there should be a Kluent version targeting it.
The goal is to not break code using the current Kluent version, which can be accomplished if junit 5 is backwards compatible.

**Comment by javatarz** [comment]
Was there a planned way to support JUnit 5? The project has a hard JUnit 4 dependency at this point. I'm wondering if Kluent needs a major version bump as well.

I need this fix for a project and I'm hoping to contribute a PR. I was hoping to get @MarkusAmshove's feedback before implmenting any of it.

**Comment by MarkusAmshove** [comment]
I think we want a major version bump, because it might be a breaking change (I'm not too familiar with JUnit5 at the moment).

I'm also not sure how it works together with Spek which we use for our tests.

I would appreciate a PR because I'm on a full schedule at the moment :)

**Comment by javatarz** [comment]
AFAIK Spek is only a test runner and does not come with an assertion library (something I appreciate). I tend to use Spek as my test runner and Kluent as my assertion library of choice on my Kotlin projects.

I have seen projects have a major version bump for these things but it's essentially a fork. For the foreseeable future, you'd be maintaining 2 projects. If there is a new feature being added, you'd be adding it to both Kluent 1.x (which uses JUnit 4) and Kluent 2.x (which uses JUnit 5).

I'm happy to submit a PR if you'd have some time to merge and publish a newer artifact. Thanks for the quick response. I'll work on a PR and send it soon :)

**Comment by javatarz** [comment]
I think we should close this task because it's clear that a JUnit 5 is not making it's way into Kluent.

The consensus seems to be to make Kluent independent of test runners (PR #72) and have this work tracked through issue #75.

@MarkusAmshove: Can we close this task?

**Comment by MarkusAmshove** [comment]
Oops, forgot it was still open :-)
