### ISSUE TITLE
Can't assert throwables

### ISSUE THREAD

**Issue by westonal** [MarkusAmshove/Kluent#40]
All exception checking is restricted to `Exception`s:

    infix fun <T : Exception> (() -> Any).`should throw`(expectedException: KClass<T>) {

Where they need to be less restriced to the superclass of `Exception` which is `Throwable` in order to assert any `throw` statement at all.

    infix fun <T : Throwable> (() -> Any).`should throw`(expectedException: KClass<T>) {

Example failing (to compile) usecases:

    @Test
    fun `should throw uncompilable example`() {
        {
            1 `should be` 2
        } `should throw` AssertionError::class
    }

    @Test
    fun `pure example of should throw uncompilable`() {
        {
            throw Throwable()
        } `should throw` Throwable::class
    }

But this is fine:

    @Test(expected = AssertionError::class)
    fun `assertion error (throwable) example`() {
            1 `should be` 2
    }

    @Test(expected = Throwable::class)
    fun `pure throwable example`() {
        throw Throwable()
    }

**Comment by MarkusAmshove** [comment]
Youre right, I will change it. Thansks for reporting :)

**Comment by MarkusAmshove** [comment]
I've released the fix in 1.20, could you confirm this?

**Comment by westonal** [comment]
Yeah, works great, thankyou!
