### ISSUE TITLE
documentation: verify-mockedMethod-has-been-called-n-times

### ISSUE THREAD

**Issue by bastman** [MarkusAmshove/Kluent#49]
Hi Marcus, I'm a big fan of your library.

But could you please add an example on how to verify that a mocked/stubbed method call has been called n-times.

I'm currently struggling with ...

Verify on apiClient that
            apiClient.sendRequest(any()) was called

This asserts method is called exactly once.
But I'd like to assert, that method has been called 2-times or not-more-than-2-times.

Is there an idiomatic way to to that kind of stuff?

Thanks a lot for your help
/Seb

**Comment by MarkusAmshove** [comment]
Hi Seb,

sorry for the late reply.

At the moment it seems like we don't support this, but I'll look into it as soon as possible :-)

**Comment by bastman** [comment]
Hi Markus, thanks a lot. Looking forward.

**Comment by MarkusAmshove** [comment]
At the moment I don't see how I could make this working with a nice syntax.

The way mockito expects the call in this case is

`verify(apiClient, 2).sendRequest(any())`

which means that we would have to include the number (or methods like atLeast, atMost etc) when calling the Verify.

`Verify on mock` the function behind this is the on function, giving it more than one parameter would break the infix notation.

I'll leave the issue open, maybe someone will have an idea in the future :-)

In the meantime you could use [mockito-kotlin](https://github.com/nhaarman/mockito-kotlin) which we also use under the hood, maybe you like their syntax better than the Java one

**Comment by MarkusAmshove** [comment]
I'm going to close this since we can't implement this with infix functions
