### ISSUE TITLE
can't use Kluent in Android Instrumentation test

### ISSUE THREAD

**Issue by mateherber** [MarkusAmshove/Kluent#53]
Kluent has lots of java8 APIs and while using proguard I could build
-dontwarn org.amshove.kluent.**

I could not deploy the tests to the device:

INSTALL_FAILED_DEXOPT
Unknown failure (Failure - not installed for 0)

It'd be nice to have an kluent-android which supports instrumentation tests

**Comment by MarkusAmshove** [comment]
Hi, 

I'm not developing for android, but I like the idea. 
In my understanding, kotlin will/can compile to Android compatible byte code, but we're using features that aren't usable on Android. 
Can you hint me to some things in Kluent that don't work with kotlin? Is there a way to set up intellij to warn about such APIs? (maybe setting source compatibility in gradle) 

_Sent from my Vernee Apollo Lite using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mateherber** [comment]
Honestly I don't exactly know how can you make a "vanilla" java library android compatible. For android libraries we usually use the apply plugin: 'com.android.library' gradle plugin which has 

sourceCompatibility JavaVersion.VERSION_1_7
targetCompatibility JavaVersion.VERSION_1_7

But on Android we don't even have the full 1.7 framework since for instance modern time api which is supported in Kluent is not present on Android (org/amshove/kluent/DateTime.kt)

I'll try to create a fork and play around a bit to see if I can compile to android compatible version by adding the android gradle plugin and removing the not supported references and then next steps can be taken.

**Comment by MarkusAmshove** [comment]
This is a good idea. 
We might be at a point to consider pulling Kluent out into an organization in Github, since we would have at least 2 projects to maintain (also maybe native and js if there is demand) 

_Sent from my Vernee Apollo Lite using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MarkusAmshove** [comment]
Thanks to @eburke56 ([PR](https://github.com/MarkusAmshove/Kluent/pull/58)) we now have an artifact specifically for Android.

Example:
```testImplementation 'org.amshove.kluent:kluent-android:1.28'```
