### ISSUE TITLE
Use mockito-kotlin-kt1.1

### ISSUE THREAD

**Issue by NoahAndrews** [MarkusAmshove/Kluent#61]
Version 1.5.0 of mockito-kotlin introduced a new artifact for Kotlin 1.1. Since this project already depends on Kotlin 1.1, shouldn't we be using this new artifact?

**Comment by MarkusAmshove** [comment]
We should definitely do this, I was waiting for them to release an artifact with 1.1, because at the moment we have multiple runtime versions (>=1.1 and 1.0)

**Comment by MarkusAmshove** [comment]
I've updated mockito-kotlin with the latest commit. The next release will use the mockito-kotlin-kt1.1 package
