### ISSUE TITLE
Wrong Verify

### ISSUE THREAD

**Issue by JcMinarro** [MarkusAmshove/Kluent#62]
The Verify is not working fine when you use `com.nhaarman.mockito_kotlin.check` as a mock argument.
I have created a repo where I do the same test with and without Kluent where you could check the behavior that I describe here
https://github.com/JcMinarro/TestKluent

**Comment by MarkusAmshove** [comment]
after some testing I've finally found the issue.

Using
```kt
@Test
    fun `This test should fail because the inversion check is wrong Kluent`() {
        val input = Input(true, false)
        someClass.invert(input, callback)
        Verify on callback that callback.result(check {
            it.bar `should be` input.bar
            it.foo `should be` input.foo
        }) was called
    }
```

will work. Notice the `on` within the `Verify`.

[This](https://github.com/MarkusAmshove/Kluent/blob/master/src/main/kotlin/org/amshove/kluent/Mocking.kt#L17) "starts" the mocking. Without the `on` [this](https://github.com/MarkusAmshove/Kluent/blob/master/src/main/kotlin/org/amshove/kluent/Mocking.kt#L21) was invoked, which doesn't actually check anything.

I'll try to work on a constraint that would prevent this in the future

**Comment by JcMinarro** [comment]
Thank.

Would be great to have that constraint

**Comment by MarkusAmshove** [comment]
I've found out that with mockito you can check if something really is a mock.

I've come up with a check in a few of methods to ensure that we're dealing with a mock (that the `on` was specified).

Would this as an error be enough of an explanation? It sadly has to be a runtime check

![image](https://user-images.githubusercontent.com/2401875/30601887-4e0f992e-9d63-11e7-87ea-106a08fe700c.png)

**Comment by JcMinarro** [comment]
I think it is good enough. I would try to change the method name for something more generic.
The perfect way was a "Lint Error", but I am not sure if it is possible in the library.
BTW, I am sure that a lot of people has `Verify that mock.method() was called` on their tests and the assertion is not working. If they update Kluent to a new version with this patch, their tests are going to fail, but it is good, because the assertion wasn't working.
