### ISSUE TITLE
Should Throw Used to be able to catch AssertionExceptions

### ISSUE THREAD

**Issue by westonal** [MarkusAmshove/Kluent#65]
This used to work (1.21), now it leaks the exception (1.29).

    @Test
    fun `Catch assertion exception`() {
        {
            assertEquals("!", "@")
        } `should throw` AssertionError::class
    }

Sorry, maybe that didn't work in 1.21, but this did:

    @Test
    fun `Catch assertion exception (the exception)`() {
        {
            assertEquals("!", "@")
        } `should throw the Exception` AssertionError::class
    }

**Comment by MarkusAmshove** [comment]
Hi @westonal ,

this should still work, but is deprecated:

![screenshot_20170927_200745](https://user-images.githubusercontent.com/2401875/30929748-b7e1392c-a3bf-11e7-9273-bf56c49cb2ab.png)

**Comment by westonal** [comment]
OK, but does:

```
@Test
fun `Catch assertion exception`() {
    {
        assertEquals("!", "@")
    } `should throw` AssertionError::class
}
```

work for you?

**Comment by MarkusAmshove** [comment]
![image](https://user-images.githubusercontent.com/2401875/31011062-462260aa-a50d-11e7-9251-7e804a41d0b7.png)

This does also work as expected (the `AssertionError` is thrown, so the test passes).

What result do you expect in this case?

**Comment by westonal** [comment]
Yes, that's what I expect to happen, I will do more investigation then.

**Comment by MarkusAmshove** [comment]
Is your code that is causing issues in any repository I can download and test out?

 

Von: Alan Evans [mailto:notifications@github.com] 
Gesendet: Freitag, 29. September 2017 13:11
An: MarkusAmshove/Kluent <Kluent@noreply.github.com>
Cc: Markus Amshove <scm@amshove.org>; Comment <comment@noreply.github.com>
Betreff: Re: [MarkusAmshove/Kluent] Should Throw Used to be able to catch AssertionExceptions (#65)

 

Yes, that's what I expect to happen, I will do more investigation then.

**Comment by westonal** [comment]
No, but I will try to create an [MCVE](https://stackoverflow.com/help/mcve) which you can checkout. And if I can't, then I'll narrow down the issue. Either way will update this issue shortly.

**Comment by westonal** [comment]
Why can't we catch all throwables? Seems like an easy fix. I'm writing my own extensions and I'm forced to write `@Test(expected = AssertionError::class)` like the old days.

```
infix fun KClass<*>.`should be assignable from`(kClass: KClass<*>) {
    this.java.isAssignableFrom(kClass.java) `should be` true
}

class AssignableAssertionsTest {

    private interface I
    private class A : I
    private class B

    @Test
    fun `true`() {
        I::class `should be assignable from` A::class
    }
    @Test(expected = AssertionError::class)
    fun `false`() {
        I::class `should be assignable from` B::class
    }
}
```

`should throw` et al. seem unnecessarily strict.

**Comment by MarkusAmshove** [comment]
I'll have another look soon (moving atm) and see what I can do.

I have to revisit exceptions anyway, because of the movement to multiplatform.

At the moment we would have to catch `Throwable`, because there is no way to genereically see the base exception from the current executing testframework.
