### ISSUE TITLE
Numerical assertions > Special case > shouldNotBe* not implemented

### ISSUE THREAD

**Issue by ersin-ertan** [MarkusAmshove/Kluent#67]
Trying out docs, and these two functions are not implemented in version 1.29
Was this to force the usage of 'should be' instead of 'should not be', due to its boolean nature?
```kotlin
(-2).shouldNotBePositive()
2.shouldNotBeNegative()
```

**Comment by MarkusAmshove** [comment]
I remember that I wrote the docs first and when implementing `shouldBePositive` and `shouldBeNegative` I thought that they're already negating each other.

Do you think it would be worth to also have `shouldNotBePositive` and `shouldNotBeNegative`?

It could have a different meaning for the reader to say "this should be negative" or "this should not be positive", since both cases don't include 0.

**Comment by ersin-ertan** [comment]
Consider:
```kotlin
var a:Boolean? = null
println( if(a == true) a else a)
```
This expression is dealing with three states: true, false and null

We can call `a shouldNotBe true` without error because junit is comparing the reference using `if (unexpected == actual)`. However, `a?.shouldNotBeTrue()`, explicitly provides a value to compare, if we called it, there is no meaning because the function is not executed on a null value.

Switching to the numerical context you are dealing with 4 states: negative, 0, positive, and null. `shouldBeGreaterThan 0` and `shouldNotBeLessOrEqualTo(0)` are the same, so adding `shouldBePositive()` would be redundant(because you would have many ways to say the same thing, including `shouldNotBeNegative`), **unless** `shouldNotBeNegative()` would cover nullable types. An `Int?` with the value of 1 or `null` is not negative. 

This starts to get confusing when you have `shouldNotBeLessThan 0` and `shouldBeGreaterOrEqualTo(0)`

This is made explicit with CharSequence assertions `name.shouldNotBeNullOrEmpty()`

I thinks it's perfectly ok to constrict the greater and less than keywords to non-nullable type, because they have a 1:1 correspondence with our logical symbols, <,>,<=, >=.
But when introducing keywords like positive and negative along with Not, it should include nullable types.

**Comment by MarkusAmshove** [comment]
Thank you for your opinion, very interesting read! :-)

I'll get rid of the negations of positive and negative in the docs
