### ISSUE TITLE
Assertion error shows precious element as incorrect

### ISSUE THREAD

**Issue by Viterzgir666** [MarkusAmshove/Kluent#69]
Hi! 
Steps to reproduce: 
1. import org.amshove.kluent.shouldEqual to your project
2. Create 2 arrays, e.g.
`val arrayOne= arrayOf("One", "Two", "Three")`
`val arrayTwo= arrayOf("One", "Two", "Four")`
3. Compare 2 arrays with `shouldEqual`

Actual result: 
```
arrays first differed at element [2]; 
Expected :[Four]
Actual   :[Three]

```
error appeared. Error says that arrays differed at element 2. 

Expected result: Correct element number should be shown in assertion error. 

Thanks for your product!

**Comment by goreRatzete** [comment]
I think 2 refers to the index in the array. Since it is zero-based, arrayOne[2] yields "Three" and arrayTwo[2] yields "Four".

**Comment by Viterzgir666** [comment]
Oh, oops. you're right. my first issue on GitHub and I messed up :D 

Sorry, for disturbing :)
