### ISSUE TITLE
shouldThrow should use exception class hierarchy instead of exact class

### ISSUE THREAD

**Issue by neyb** [MarkusAmshove/Kluent#7]
`{ throw IllegalStateException() } shouldThrow RuntimeException::class` should pass

**Comment by MarkusAmshove** [comment]
(for the record)
I've tested what JUnits behavior would be in this case.

This test passes:
`@Test(expected = RuntimeException.class)
    public void test()
    {
        new ArrayList<>().get(0);
    }`

So the Exceptionhierarchy is expected behavior

**Comment by MarkusAmshove** [comment]
I merged your PR into master and released both changes into 1.9. 

Thanks for your contribution!
