### ISSUE TITLE
Missing assertions

### ISSUE THREAD

**Issue by mreparaz** [MarkusAmshove/Kluent#70]
I have some function that returns a nullable object and, in certain conditions, throws an exception. 
`fun someFunction(param: Int): SomeType?`
So, I do 
`val theFunction = { someFunction(-1) }`
but the type of `theFunction` is `() -> Any?` and doesn't apply the `should throw` assertion because it's expects `() -> Any`.
`theFunction shouldThrow RuntimeException::class` // doesn't work
It's possible to add this assertions?

**Comment by goreRatzete** [comment]
I believe this was recently fixed in #63 .

What version are you using? The fix is in 1.30.

**Comment by MarkusAmshove** [comment]
@goreRatzete  is correct, it should be included in 1.30. Have a look the super awesome formatted [changelog](https://markusamshove.github.io/Kluent/) :-P
