### ISSUE TITLE
Android 1.31 version have null inside inner dependencies versions

### ISSUE THREAD

**Issue by caipivara** [MarkusAmshove/Kluent#79]
If you check the pom for that version on bintray you can see:

Library: ```'org.amshove.kluent:kluent-android:1.31'```

Library pom example:
```
 <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
      <version>null</version>
      <scope>runtime</scope>
...
```

And then this version is not usable.

**Comment by MarkusAmshove** [comment]
Good catch. I don't think we changed anything on the Gradle side.
I'll have a look into it

**Comment by MarkusAmshove** [comment]
There was an issue with the way the Bintray plugin resolved the versions of our dependencies.
I've rereleased 1.31, can you verify that it works now?

**Comment by caipivara** [comment]
@MarkusAmshove thanks, it works now
