### ISSUE TITLE
Iterable<T>.shouldContainAll doesn't work with Arrays

### ISSUE THREAD

**Issue by goreRatzete** [MarkusAmshove/Kluent#82]
I always have to convert to List first. 
`conf.options shouldContainAll options.toList()`

Would be nice to have an overload with Arrays.

**Comment by MarkusAmshove** [comment]
This should work with all different collectionlike assertions, right?

**Comment by goreRatzete** [comment]
Yes, I would say so. The more work we can take off the user, the better.

**Comment by MarkusAmshove** [comment]
I've just released v1.32 which contains these changes 👍
