### ISSUE TITLE
Failed to resolve mockito-kotlin dependency

### ISSUE THREAD

**Issue by Jeevuz** [MarkusAmshove/Kluent#86]
Hi! 
I have
```
Error:Failed to resolve: com.nhaarman:mockito-kotlin-kt1.1:1.5.+
```
in the version 1.32. 

I think it's because of 1.5.+ versioning.

Excluding the module and adding dependency with 1.5.0 solves the issue.

**Comment by MarkusAmshove** [comment]
Hello!

Did you try to build Kluent itself or did this come up in another project?

I've just deleted all my cached artifacts locally and built Kluent from scratch via gradle and didn't have any problems.

**Comment by Jeevuz** [comment]
All was ok on the version 1.30. Then I updated it and catch the error. So I think It is because of it. I have Studio 3.0.1, plugin 3.0.1, Kotlin 1.21. Maybe it's because of something of that?

**Comment by Jeevuz** [comment]
Checked again on my home notebook and have the same error.

**Comment by magneticflux-** [comment]
Any idea what could cause this? Did the other project get shut down for some reason?

**Comment by MarkusAmshove** [comment]
Is this on Android projects?

**Comment by magneticflux-** [comment]
My project is a pure Kotlin project. @Jeevuz seems to have an Android project.

**Comment by MarkusAmshove** [comment]
I've just checked the generated POM in bintray and it contains a `+` since the last release.

That shouldn't happen, because even if it works it might be unstable if we have a tested Kluent version which uses a brocken mockito-kotlin version that way.

I'll get this resolved ASAP

**Comment by MarkusAmshove** [comment]
I've released 1.33, which contains fixed versions in the POM.

Can you try it out? It is available for plain JVM and Android

**Comment by Jeevuz** [comment]
Yep, now all is ok!

**Comment by MarkusAmshove** [comment]
Thanks for confirming :-)
