### ISSUE TITLE
Add backtick version of VerifyNotCalled

### ISSUE THREAD

**Issue by athkalia** [MarkusAmshove/Kluent#87]
Seems like this one is missing or maybe I couldn't find it. Can you add it in?

**Comment by MarkusAmshove** [comment]
Hi, you're right, the backtick and not backtick mockings are inconsistent in that regard.

U'll address this in the next version.

| Non backtick | backtick |
|---|---|
| When | not needed |
| Verify | not needed |
| VerifyNotCalled | not implemented |
| called | not needed | 
| VerifyNoInteractions | `Verify no interactions` |
| VerifyNoFurtherInteractions | `Verify no further interactions` |

**Comment by athkalia** [comment]
sounds good pal, thanks a lot

**Comment by MarkusAmshove** [comment]
I've just released it with 1.33 :-)
