### ISSUE TITLE
Iterable<T> return types have to be revisited

### ISSUE THREAD

**Issue by goreRatzete** [MarkusAmshove/Kluent#93]
I was just messing with the latest
`fun <T> Iterable<T>.shouldNotBeEmpty() = this.apply { assertNotEmpty(this, "Iterable") }`

my code looks like this:
```
LovMapper()
            .getTypes()
            .groupBy(RelationTable::country)["DK"]
            .shouldNotBeNull()
            .shouldNotBeEmpty()
            .forEach(::println)
```

I noticed that the `shouldNotBeEmpty` call returns an `Iterable`, no matter what the actual receiver type is. 

Most of the `Iterable` funs could be changed to something like this:
`fun <R: Iterable<*>> R.shouldNotBeEmpty(): R = apply { ... }`

In this way, they preserve the actual type.

**Comment by MarkusAmshove** [comment]
You're right, that makes more sense now with chaining calls.
I'll get onto it this weekend

**Comment by MarkusAmshove** [comment]
You're right, that makes more sense now with chaining calls.
I'll get onto it this weekend

**Comment by MarkusAmshove** [comment]
You're right, that makes more sense now with chaining calls.
I'll get onto it this weekend

**Comment by MarkusAmshove** [comment]
I've just released a new version with only this change in it, because it's almost been one month and I was waiting for other issues/features, but nothing came
